name: Build Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[1-9][0-9]*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v3
        name: Validate Gradle Wrapper

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Build Candidate
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-rc')
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: |
          ./gradlew -Prelease.useLastTag=true build candidate --stacktrace --scan

      - name: Build Final
        if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-rc')
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: |
          ./gradlew -Prelease.useLastTag=true build final --stacktrace --scan
