# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: "11"
        distribution: "temurin"
        cache: "gradle"
    - name: Build
      run: ./gradlew clean build testGradle8.4
    - name: Archive Codenarc Report on Failure
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: codenarc-results
        path: build/reports/codenarc
    - name: Archive Test Results on Failure
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: ${{ matrix.os }}-ci-test-results
        path: build/reports/tests
