# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Regression

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        gradle_version: ["6.3", "6.4.1", "7.4"]
        java: [8, 11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: "temurin"
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: ${{ runner.os }}-gradle 
    - name: Test ${{ matrix.gradle_version }}
      run: ./gradlew testGradle${{ matrix.gradle_version }}
    - name: Archive Test Results
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: test-results
        path: build/reports/tests
