# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Regression

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        gradle_version: ["7.1.1", "8.0.2"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: "11"
        distribution: "temurin"
        cache: "gradle"
    - name: Test ${{ matrix.gradle_version }}
      run: ./gradlew testGradle${{ matrix.gradle_version }}
    - name: Archive Test Results on Failure
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: ${{ matrix.os }}-${{ matrix.gradle_version }}-test-results
        path: build/reports/tests
